# Generated by Django 3.1.1 on 2020-11-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionInstance',
            fields=[
                ('mission_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('norad_id', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('mission_timer', models.IntegerField(default=0)),
                ('tle_line_1', models.CharField(blank=True, max_length=70)),
                ('tle_line_2', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=24)),
                ('satellite_tle1', models.CharField(max_length=70)),
                ('satellite_tle2', models.CharField(max_length=70)),
                ('norad_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.IntegerField(default=0)),
                ('geometry', models.CharField(blank=True, max_length=4096)),
                ('subsystems', models.CharField(blank=True, max_length=4096)),
                ('instruments', models.CharField(blank=True, max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='UserInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128, null=True, unique=True)),
                ('mission_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.missioninstance')),
            ],
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='satellite_ref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.satelliteinstance'),
        ),
    ]
