# Generated by Django 2.2.6 on 2019-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=24)),
                ('satellite_tle1', models.CharField(max_length=70)),
                ('satellite_tle2', models.CharField(max_length=70)),
            ],
        ),
    ]
