# Generated by Django 2.2.6 on 2019-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('satellite_number', models.IntegerField(primary_key=True, serialize=False)),
                ('satellite_name', models.CharField(max_length=24)),
                ('satellite_class', models.CharField(max_length=1)),
                ('launch_year', models.IntegerField()),
                ('launch_count', models.IntegerField()),
                ('launch_item', models.CharField(max_length=1)),
                ('epoch_year', models.IntegerField()),
                ('epoch_date', models.FloatField()),
                ('mean_motion_first_derivative', models.FloatField()),
                ('mean_motion_second_derivative', models.FloatField()),
                ('drag_term', models.FloatField()),
                ('tle_set_number', models.IntegerField(default=0)),
                ('inclination', models.FloatField()),
                ('ra_ascending_node', models.FloatField()),
                ('eccentricty', models.FloatField()),
                ('argument_of_perigee', models.FloatField()),
                ('mean_anomaly', models.FloatField()),
                ('mean_motion', models.FloatField()),
                ('revolutions_count', models.IntegerField()),
            ],
        ),
    ]
