# Generated by Django 2.2.6 on 2019-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='norad_id',
            field=models.IntegerField(default=0),
        ),
    ]
