# Generated by Django 3.1.1 on 2020-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('mission_name', models.CharField(blank=True, max_length=255)),
                ('initial_setup', models.CharField(blank=True, max_length=4096)),
                ('objectives', models.CharField(blank=True, max_length=4096)),
            ],
        ),
    ]
