# Generated by Django 3.1.1 on 2020-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0003_missionscenario_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionscenario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='missionscenario',
            name='satellite_id',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='id',
        ),
        migrations.AddField(
            model_name='missionscenario',
            name='scenario_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='norad_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
