# Generated by Django 3.1.1 on 2020-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0003_missioninstance_satelliteinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioninstance',
            name='mission_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='norad_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='tle_line_1',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='tle_line_2',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='satelliteinstance',
            name='geometry',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='satelliteinstance',
            name='instruments',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='satelliteinstance',
            name='subsystems',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
