# Generated by Django 3.1.1 on 2020-11-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0004_auto_20201104_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('mission_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.missioninstance')),
            ],
        ),
    ]
