# Generated by Django 3.1.1 on 2020-10-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0004_auto_20201012_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioninstance',
            name='satellite_ref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.satelliteinstance'),
        ),
    ]
