# Generated by Django 3.1.1 on 2020-11-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0005_missioneventlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstance',
            name='mission_ref',
        ),
    ]
