# Generated by Django 3.1.1 on 2020-11-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0006_remove_userinstance_mission_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioninstance',
            name='scenario_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.missionscenario'),
        ),
        migrations.AddField(
            model_name='missioninstance',
            name='user_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.userinstance'),
        ),
    ]
