# Generated by Django 3.1.1 on 2020-11-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0006_auto_20201101_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstance',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
