# Generated by Django 3.1.1 on 2020-12-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0007_auto_20201127_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='geometry_definition',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='satellite',
            name='instrument_definition',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='satellite',
            name='system_definition',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
