# Generated by Django 3.2 on 2021-04-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundsim', '0009_auto_20201215_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteOrbitTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('satellite_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groundsim.satellite')),
            ],
        ),
    ]
